### ISSUE TITLE
Operator: tmforumodacanvas/component-controller Pod fails into CrashLoopBackOff.

### ISSUE THREAD

**Issue by tomkivlin** [tmforum-oda/oda-ca#46]
## Description

When installing the Canvas, the `tmforumodacanvas/component-controller` Pod fails into `CrashLoopBackOff`. The logs show:

```
[2021-05-26 08:32:35,111] ComponentOperator    [INFO    ] Monitoring namespace components
Logging set to  20
Ingress set to  nginx
Traceback (most recent call last):
  File "/usr/local/bin/kopf", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kopf/cli.py", line 57, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kopf/cli.py", line 102, in run
    modules=modules,
  File "/usr/local/lib/python3.7/site-packages/kopf/_cogs/helpers/loaders.py", line 38, in preload
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "securityController/securityControllerKeycloak.py", line 8, in <module>
    from .secconkeycloak import Keycloak
ModuleNotFoundError: No module named '__kopf_script_2__securityController/securityControllerKeycloak'
```

Suspect that

```
    from .secconkeycloak import Keycloak
```

Needs to change to

```
    from secconkeycloak import Keycloak
```

Have tried that locally and the above error is not raised.

**Comment by tomkivlin** [comment]
Also, curiously, the code in the `tmforumodacanvas/component-controller:latest` image is different to the code on the master branch here: https://github.com/tmforum-oda/oda-ca/tree/master/controllers

**Comment by tomkivlin** [comment]
I would raise a PR but suspect `latest` is being built from a different branch so don't want to break anything.

**Comment by LesterThomas** [comment]
I think I created this problem - I changed the import statement (as part of creating the documentation - the documentation creates code-level documentation by importing the python modules). My test must of not re-built/used the updated docker images which is why I didn't pick it up.

**Comment by LesterThomas** [comment]
I'll attempt a fix - I need to find an import mechanism that works with the documentation and the actual controller.

**Comment by tomkivlin** [comment]
Thanks @LesterThomas
